* Hans' simple corrections
**
"The idea of the name being that h~1/n? Might be good to state that." But
at this point we aren't talking about elements, so there is no "h".

** 116-1
 correction doesn't seem to make sense.
** I assume 129-1 doesn't require any changes.
We have eliminated any parameters which affect the time scales, so we don't need to experiment with that.
** 140-1:
 no, what I wrote is correct (the implicit RK way of writing IMR is a bit weird)
** 143-2:
I think the question is: "Should the Newton divided differences really have an increasing number of arguments as the order of the derivative increases?", in which case the answer is yes: more points are needed to compute higher order derivatives. Also yes this is the conventional notation (see e.g. the reference below the definition).
** 184-1: The comment just says "Q:"

* Finding a citation for order of direct methods

** Seems to be hard, no one gives concrete numbers!

** I can derive estimate for simple case:

*** Isereles gives banded matrix: O(s^2d) where s is bandwidth and d is nrow.

*** In 1D bandwidth is O(1)

*** In 2D for a regular grid the bandwidth is ~ sqrt(n) (in a grid of nodes neighbouring lines of nodes must connect with each other, each "line" hase ~sqrt(n) entries).

*** But changes for 3D, grid structure, element type...  too complex to give a rough rule of thumb for?



* What do packages do for renorm?

** magpar:
renormalise if worse than tol function in:
/home/david/Downloads/magpar-0.9/src/util/renormvec.c

called by PVodeReInit and by CheckIterationLLG

CheckIterationLLG seems to be the main llg function (called inside loop in main.c)

** nmag:
uses modified LLG function (cite Hans priv. comm.)

** oommf
*** Uses either renorm onto sphere (for euler) or renorm after each step (for RK4).
*** Options for other methods in new releases.
*** cite M Donahue priv. comm., store the email here?

** femme:
unknown, probably works in the same way as magpar, ask someone?


* What do packages do for non-linear and/or linear solve

** magpar:
Cites Vassilio's paper, so probably does that.

Looks like Hans was right: they drop the magnetostatic part from the
Jacobian (Suess2002a: Nucleation in polycrystalline thin films using a
preconditioned finite element method). It's very badly written in the
Suess2002 paper, which confused me...

The preconditioner used is ILU.


This is a bit weird because Schrefl published a paper in 1997 using
semi-explicit BEM magnetostatics similar to mine (A Higher Order FEM-BEM
Method for the Calculation of Domain Processes in Magnetic Nano-Elements).
The only thing missing from that paper is extrapolation and he would have a
much more efficient way to solve the equations...

Should I ask him why he did this?


** nmag:
Uses d'Aquino's approach (cite Hans priv. comm.)

** femme:
Unknown, probably works in the same way as magpar, ask someone?
